/**********************************************************************
 *
 * This file is part of the AWeb-II distribution
 *
 * Copyright (C) 2002 Yvon Rozijn
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the AWeb Public License as included in this
 * distribution.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * AWeb Public License for more details.
 *
 **********************************************************************/

/* html.h - AWeb HTML markup and attributes */

#ifndef HTML_H
#define HTML_H

enum MARKUP_TYPES
{  MARKUP_UNKNOWN=0,MARKUP_TEXT,MARKUP_EOF,
   MARKUP_HTML,MARKUP_HEAD,MARKUP_TITLE,MARKUP_BASE,MARKUP_ISINDEX,
   MARKUP_BODY,MARKUP_H1,MARKUP_H2,MARKUP_H3,MARKUP_H4,MARKUP_H5,MARKUP_H6,
   MARKUP_P,MARKUP_BR,MARKUP_HR,
   MARKUP_ADDRESS,MARKUP_BLOCKQUOTE,MARKUP_XMP,MARKUP_LISTING,
   MARKUP_UL,MARKUP_OL,MARKUP_LI,MARKUP_DIR,MARKUP_MENU,
   MARKUP_DL,MARKUP_DT,MARKUP_DD,
   MARKUP_CITE,MARKUP_CODE,MARKUP_DFN,MARKUP_EM,MARKUP_KBD,MARKUP_PRE,
   MARKUP_SAMP,MARKUP_STRONG,MARKUP_VAR,MARKUP_TT,
   MARKUP_B,MARKUP_I,MARKUP_U,MARKUP_STRIKE,
   MARKUP_A,MARKUP_IMG,
   MARKUP_FORM,MARKUP_INPUT,MARKUP_SELECT,MARKUP_OPTION,MARKUP_TEXTAREA,
   MARKUP_BUTTON,
   MARKUP_ICON,MARKUP_SCRIPT,
   MARKUP_CENTER,MARKUP_DIV,MARKUP_STYLE,
   MARKUP_TABLE,MARKUP_TR,MARKUP_TD,MARKUP_TH,MARKUP_CAPTION,
   MARKUP_COLGROUP,MARKUP_COL,
   MARKUP_THEAD,MARKUP_TFOOT,MARKUP_TBODY,
   MARKUP_MAP,MARKUP_AREA,
   MARKUP_FONT,MARKUP_BASEFONT,MARKUP_BIG,MARKUP_SMALL,MARKUP_SUB,MARKUP_SUP,
   MARKUP_BGSOUND,
   MARKUP_FRAME,MARKUP_FRAMESET,MARKUP_NOFRAMES,
   MARKUP_META,MARKUP_LINK,
   MARKUP_NOBR,MARKUP_WBR,MARKUP_BLINK,
   MARKUP_OBJECT,MARKUP_PARAM,MARKUP_EMBED,
   MARKUP_NOSCRIPT,
   MARKUP_IFRAME,
   MARKUP_INS,MARKUP_DEL,
};

#define MARKUP_MASK        0x7fff   /* identifying part */
#define MARKUP_END         0x8000   /* markup is end tag */

struct Tagattr             /* an attribute to a markup tag */
{  NODE(Tagattr);          /* list node */
   UWORD attr;            /* attribute code, see below */
   long valuepos;          /* position in args buffer -or- string ptr for ICON*/
   long length;            /* length of arg value */
};

enum TAG_ATTRIBUTES
{  TAGATTR_BACKGROUND=1,TAGATTR_BGCOLOR,TAGATTR_TEXT,TAGATTR_LINK,TAGATTR_VLINK,
   TAGATTR_ALINK,TAGATTR_ALIGN,
   TAGATTR_HREF,TAGATTR_NAME,TAGATTR_TITLE,TAGATTR_ID,
   TAGATTR_SRC,TAGATTR_ALT,TAGATTR_ISMAP,TAGATTR_BORDER,TAGATTR_USEMAP,
   TAGATTR_WIDTH,TAGATTR_HEIGHT,TAGATTR_HSPACE,TAGATTR_VSPACE,
   TAGATTR_SIZE,TAGATTR_NOSHADE,
   TAGATTR_PLAIN,TAGATTR_DINGBAT,TAGATTR_TYPE,TAGATTR_CONTINUE,
   TAGATTR_SEQNUM,TAGATTR_START,TAGATTR_SKIP,TAGATTR_VALUE,
   TAGATTR_ACTION,TAGATTR_METHOD,TAGATTR_ENCTYPE,
   TAGATTR_CHECKED,TAGATTR_MAXLENGTH,TAGATTR_MULTIPLE,TAGATTR_SELECTED,
   TAGATTR_COLS,TAGATTR_ROWS,
   TAGATTR_PROMPT,
   TAGATTR_CELLSPACING,TAGATTR_CELLPADDING,TAGATTR_VALIGN,
   TAGATTR_BORDERCOLOR,TAGATTR_BORDERCOLORDARK,TAGATTR_BORDERCOLORLIGHT,
   TAGATTR_NOWRAP,TAGATTR_COLSPAN,TAGATTR_ROWSPAN,
   TAGATTR_FRAME,TAGATTR_RULES,TAGATTR_SPAN,
   TAGATTR_CLEAR,
   TAGATTR_SHAPE,TAGATTR_COORDS,TAGATTR_NOHREF,
   TAGATTR_COLOR,TAGATTR_FACE,
   TAGATTR_LOOP,
   TAGATTR_LEFTMARGIN,TAGATTR_TOPMARGIN,
   TAGATTR_MARGINWIDTH,TAGATTR_MARGINHEIGHT,TAGATTR_FRAMEBORDER,TAGATTR_FRAMESPACING,
   TAGATTR_SCROLLING,TAGATTR_NORESIZE,
   TAGATTR_TARGET,
   TAGATTR_HTTP_EQUIV,TAGATTR_CONTENT,TAGATTR_REL,
   TAGATTR_DATA,TAGATTR_CODEBASE,TAGATTR_CODETYPE,TAGATTR_CLASSID,
   TAGATTR_SHAPES,TAGATTR_DECLARE,TAGATTR_STANDBY,
   TAGATTR_VALUETYPE,TAGATTR_EMBEDPARAMNAME,TAGATTR_EMBEDPARAMVALUE,
   TAGATTR_LANGUAGE,
   TAGATTR_ONLOAD,TAGATTR_ONUNLOAD,TAGATTR_ONCLICK,TAGATTR_ONMOUSEOVER,TAGATTR_ONMOUSEOUT,
   TAGATTR_ONFOCUS,TAGATTR_ONBLUR,TAGATTR_ONCHANGE,TAGATTR_ONSELECT,TAGATTR_ONRESET,
   TAGATTR_ONSUBMIT,TAGATTR_ONABORT,TAGATTR_ONERROR,
   TAGATTR_HIDDEN,
      
   TAGATTR_BR=1000,
};

#endif
