MODULES := aweblib/history.aweblib

aweblib/history.aweblib/TYPE := executable/library/amigashared
aweblib/history.aweblib/DEPS := $(MODULELIB) linklibs/libawebclib.a
aweblib/history.aweblib/CFILES := \
whistask
