MODULES := AWebPlugin/awebgif.awebplugin AWebPlugin/Docs/awebgif.html

AWebPlugin/awebgif.awebplugin/TYPE := executable/library/amigashared
AWebPlugin/awebgif.awebplugin/DEPS := $(MODULELIB) AWebPlugin/Docs/awebgif.html
AWebPlugin/awebgif.awebplugin/CFILES := \
startup awebgif gifsource gifcopy

AWebPlugin/awebgif.awebplugin/CFILES/CPPFLAGS := -I plugins/include


AWebPlugin/Docs/awebgif.html/TYPE := document
AWebPlugin/Docs/awebgif.html/FILES := \
awebgif.html awebgif.awebrx



