MODULES := aweblib/startup.aweblib

aweblib/startup.aweblib/TYPE   := executable/library/amigashared
aweblib/startup.aweblib/DEPS := $(MODULELIB)  linklibs/libawebclib.a
aweblib/startup.aweblib/CFILES := \
startup

