MODULES := linklibs/libaz.a


linklibs/libaz.a/TYPE := executable/library/link
linklibs/libaz.a/CFILES = \
adler32 compress crc32 gzio uncompr deflate trees \
zutil inflate infback inftrees inffast





