#ifndef AWEBSSL_INTERFACE_DEF_H
#define AWEBSSL_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 50.13.
** Do not edit
*/

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_AWEBSSL_H
#include <libraries/awebssl.h>
#endif

struct AwebSslIFace
{
   struct InterfaceData Data;

   ULONG APICALL (*Obtain)(struct AwebSslIFace *Self);
   ULONG APICALL (*Release)(struct AwebSslIFace *Self);
   void APICALL (*Expunge)(struct AwebSslIFace *Self);
   struct Interface * APICALL (*Clone)(struct AwebSslIFace *Self);
   void APICALL (*Assl_cleanup)(struct AwebSslIFace *Self, struct Assl * assl);
   BOOL APICALL (*Assl_openssl)(struct AwebSslIFace *Self, struct Assl * assl);
   void APICALL (*Assl_closessl)(struct AwebSslIFace *Self, struct Assl * assl);
   long APICALL (*Assl_connect)(struct AwebSslIFace *Self, struct Assl * assl, long sock, UBYTE * hostname);
   char * APICALL (*Assl_geterror)(struct AwebSslIFace *Self, struct Assl * assl, char * errbuf);
   long APICALL (*Assl_write)(struct AwebSslIFace *Self, struct Assl * assl, char * buffer, long length);
   long APICALL (*Assl_read)(struct AwebSslIFace *Self, struct Assl * assl, char * buffer, long length);
   char * APICALL (*Assl_getcipher)(struct AwebSslIFace *Self, struct Assl * assl);
   char * APICALL (*Assl_libname)(struct AwebSslIFace *Self, struct Assl * assl);
};

#endif /* AWEBSSL_INTERFACE_DEF_H */
