#ifndef AWEBPLUGIN_INTERFACE_DEF_H
#define AWEBPLUGIN_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 50.13.
** Do not edit
*/

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


struct AwebSupportIFace
{
        struct InterfaceData Data;

        ULONG APICALL (*Obtain)(struct AwebSupportIFace *Self);
        ULONG APICALL (*Release)(struct AwebSupportIFace *Self);
        void APICALL (*Expunge)(struct AwebSupportIFace *Self);
        struct Interface * APICALL (*Clone)(struct AwebSupportIFace *Self);
        ULONG APICALL (*AmethodA)(struct AwebSupportIFace *Self, struct Aobject * par1, struct Amessage * tags);
        ULONG APICALL (*Amethod)(struct AwebSupportIFace *Self, struct Aobject * par1, ...);
        ULONG APICALL (*AmethodasA)(struct AwebSupportIFace *Self, ULONG par1, struct Aobject * par2, struct Amessage * tags);
        ULONG APICALL (*Amethodas)(struct AwebSupportIFace *Self, ULONG par1, struct Aobject * par2, ...);
        APTR APICALL (*AnewobjectA)(struct AwebSupportIFace *Self, ULONG par1, struct TagItem * tags);
        APTR APICALL (*Anewobject)(struct AwebSupportIFace *Self, ULONG par1, ...);
        void APICALL (*Adisposeobject)(struct AwebSupportIFace *Self, struct Aobject * last);
        ULONG APICALL (*AsetattrsA)(struct AwebSupportIFace *Self, struct Aobject * par1, struct TagItem * tags);
        ULONG APICALL (*Asetattrs)(struct AwebSupportIFace *Self, struct Aobject * par1, ...);
        ULONG APICALL (*AgetattrsA)(struct AwebSupportIFace *Self, struct Aobject * par1, struct TagItem * tags);
        ULONG APICALL (*Agetattrs)(struct AwebSupportIFace *Self, struct Aobject * par1, ...);
        ULONG APICALL (*Agetattr)(struct AwebSupportIFace *Self, struct Aobject * par1, ULONG last);
        ULONG APICALL (*AupdateattrsA)(struct AwebSupportIFace *Self, struct Aobject * par1, struct TagItem * par2, struct TagItem * tags);
        ULONG APICALL (*Aupdateattrs)(struct AwebSupportIFace *Self, struct Aobject * par1, struct TagItem * par2, ...);
        ULONG APICALL (*Arender)(struct AwebSupportIFace *Self, struct Aobject * par1, struct Coords * par2, LONG par3, LONG par4, LONG par5, LONG par6, USHORT par7, APTR last);
        ULONG APICALL (*Aaddchild)(struct AwebSupportIFace *Self, struct Aobject * par1, struct Aobject * par2, ULONG last);
        ULONG APICALL (*Aremchild)(struct AwebSupportIFace *Self, struct Aobject * par1, struct Aobject * par2, ULONG last);
        ULONG APICALL (*Anotify)(struct AwebSupportIFace *Self, struct Aobject * par1, struct Amessage * last);
        APTR APICALL (*Allocobject)(struct AwebSupportIFace *Self, ULONG par1, LONG par2, struct Amset * last);
        ULONG APICALL (*AnotifysetA)(struct AwebSupportIFace *Self, struct Aobject * par1, struct TagItem * tags);
        ULONG APICALL (*Anotifyset)(struct AwebSupportIFace *Self, struct Aobject * par1, ...);
        APTR APICALL (*Allocmem)(struct AwebSupportIFace *Self, ULONG par1, ULONG last);
        STRPTR APICALL (*Dupstr)(struct AwebSupportIFace *Self, STRPTR par1, LONG last);
        void APICALL (*Freemem)(struct AwebSupportIFace *Self, APTR last);
        struct Coords * APICALL (*Clipcoords)(struct AwebSupportIFace *Self, struct Aobject * par1, struct Coords * last);
        void APICALL (*Unclipcoords)(struct AwebSupportIFace *Self, struct Coords * last);
        void APICALL (*Erasebg)(struct AwebSupportIFace *Self, struct Aobject * par1, struct Coords * par2, LONG par3, LONG par4, LONG par5, LONG last);
        struct Aobject * APICALL (*Aweb)(struct AwebSupportIFace *Self);
        void APICALL (*AsetattrsasyncA)(struct AwebSupportIFace *Self, struct Aobject * par1, struct TagItem * tags);
        void APICALL (*Asetattrsasync)(struct AwebSupportIFace *Self, struct Aobject * par1, ...);
        ULONG APICALL (*Waittask)(struct AwebSupportIFace *Self, ULONG last);
        struct Taskmsg * APICALL (*Gettaskmsg)(struct AwebSupportIFace *Self);
        void APICALL (*Replytaskmsg)(struct AwebSupportIFace *Self, struct Taskmsg * last);
        ULONG APICALL (*Checktaskbreak)(struct AwebSupportIFace *Self);
        ULONG APICALL (*Updatetask)(struct AwebSupportIFace *Self, struct Amessage * last);
        ULONG APICALL (*UpdatetaskattrsA)(struct AwebSupportIFace *Self, struct TagItem * tags);
        ULONG APICALL (*Updatetaskattrs)(struct AwebSupportIFace *Self, ...);
        ULONG APICALL (*Obtaintasksemaphore)(struct AwebSupportIFace *Self, struct SignalSemaphore * last);
        LONG APICALL (*Avprintf)(struct AwebSupportIFace *Self, char * par1, ULONG * last);
        LONG APICALL (*Aprintf)(struct AwebSupportIFace *Self, char * par1, ...);
        UBYTE * APICALL (*Awebstr)(struct AwebSupportIFace *Self, ULONG last);
        void APICALL (*TcperrorA)(struct AwebSupportIFace *Self, struct Fetchdriver * par1, ULONG par2, ULONG * tags);
        void APICALL (*Tcperror)(struct AwebSupportIFace *Self, struct Fetchdriver * par1, ULONG par2, ...);
        void APICALL (*TcpmessageA)(struct AwebSupportIFace *Self, struct Fetchdriver * par1, ULONG par2, ULONG * tags);
        void APICALL (*Tcpmessage)(struct AwebSupportIFace *Self, struct Fetchdriver * par1, ULONG par2, ...);
        struct Library * APICALL (*Opentcp)(struct AwebSupportIFace *Self, struct Library ** par1, struct Fetchdriver * par2, BOOL last);
        struct hostent * APICALL (*Lookup)(struct AwebSupportIFace *Self, UBYTE * par1, struct Library * last);
        BOOL APICALL (*Expandbuffer)(struct AwebSupportIFace *Self, struct Buffer * par1, long last);
        BOOL APICALL (*Insertinbuffer)(struct AwebSupportIFace *Self, struct Buffer * par1, UBYTE * par2, long par3, long last);
        BOOL APICALL (*Addtobuffer)(struct AwebSupportIFace *Self, struct Buffer * par1, UBYTE * par2, long last);
        void APICALL (*Deleteinbuffer)(struct AwebSupportIFace *Self, struct Buffer * par1, long par2, long last);
        void APICALL (*Freebuffer)(struct AwebSupportIFace *Self, struct Buffer * last);
        struct Locale * APICALL (*Locale)(struct AwebSupportIFace *Self);
        long APICALL (*Lprintdate)(struct AwebSupportIFace *Self, UBYTE * par1, UBYTE * par2, struct DateStamp * last);
        struct RastPort * APICALL (*Obtainbgrp)(struct AwebSupportIFace *Self, struct Aobject * par1, struct Coords * par2, LONG par3, LONG par4, LONG par5, LONG last);
        void APICALL (*Releasebgrp)(struct AwebSupportIFace *Self, struct RastPort * last);
        void APICALL (*Setstemvar)(struct AwebSupportIFace *Self, struct Arexxcmd * par1, UBYTE * par2, long par3, UBYTE * par4, UBYTE * last);
        void APICALL (*Copyprefs)(struct AwebSupportIFace *Self, struct AwebPrefs * par1, struct AwebPrefs * last);
        void APICALL (*Saveprefs)(struct AwebSupportIFace *Self, struct AwebPrefs * last);
        void APICALL (*Disposeprefs)(struct AwebSupportIFace *Self, struct AwebPrefs * last);
        void APICALL (*Freemenuentry)(struct AwebSupportIFace *Self, struct Menuentry * last);
        struct Menuentry * APICALL (*Addmenuentry)(struct AwebSupportIFace *Self, void * par1, USHORT par2, UBYTE * par3, UBYTE par4, UBYTE * last);
        void APICALL (*Freemimeinfo)(struct AwebSupportIFace *Self, struct Mimeinfo * last);
        struct Mimeinfo * APICALL (*Addmimeinfo)(struct AwebSupportIFace *Self, void * par1, UBYTE * par2, UBYTE * par3, UBYTE * par4, USHORT par5, UBYTE * par6, UBYTE * last);
        void APICALL (*Freenocache)(struct AwebSupportIFace *Self, struct Nocache * last);
        struct Nocache * APICALL (*Addnocache)(struct AwebSupportIFace *Self, void * par1, UBYTE * last);
        UBYTE * APICALL (*Getstemvar)(struct AwebSupportIFace *Self, struct Arexxcmd * par1, UBYTE * par2, long par3, UBYTE * last);
        void APICALL (*Freeuserbutton)(struct AwebSupportIFace *Self, struct Userbutton * last);
        struct Userbutton * APICALL (*Adduserbutton)(struct AwebSupportIFace *Self, void * par1, UBYTE * par2, UBYTE * last);
        void APICALL (*Freepopupitem)(struct AwebSupportIFace *Self, struct Popupitem * last);
        struct Popupitem * APICALL (*Addpopupitem)(struct AwebSupportIFace *Self, void * par1, USHORT par2, UBYTE * par3, UBYTE * last);
        UBYTE * APICALL (*Awebversion)(struct AwebSupportIFace *Self);
        long APICALL (*Syncrequest)(struct AwebSupportIFace *Self, UBYTE * par1, UBYTE * par2, UBYTE * last);
        UBYTE * APICALL (*PprintfA)(struct AwebSupportIFace *Self, UBYTE * par1, UBYTE * par2, UBYTE ** tags);
        UBYTE * APICALL (*Pprintf)(struct AwebSupportIFace *Self, UBYTE * par1, UBYTE * par2, ...);
        ULONG APICALL (*Today)(struct AwebSupportIFace *Self);
        void APICALL (*Freeuserkey)(struct AwebSupportIFace *Self, struct Userkey * last);
        struct Userkey * APICALL (*Adduserkey)(struct AwebSupportIFace *Self, void * par1, USHORT par2, UBYTE * last);
        long APICALL (*LprintfA)(struct AwebSupportIFace *Self, UBYTE * par1, UBYTE * par2, void * tags);
        long APICALL (*Lprintf)(struct AwebSupportIFace *Self, UBYTE * par1, UBYTE * par2, ...);
        BOOL APICALL (*Fullversion)(struct AwebSupportIFace *Self);
        void APICALL (*Setfiltertype)(struct AwebSupportIFace *Self, void * par1, UBYTE * last);
        void APICALL (*Writefilter)(struct AwebSupportIFace *Self, void * par1, UBYTE * par2, long last);
        long APICALL (*Awebcommand)(struct AwebSupportIFace *Self, long par1, UBYTE * par2, UBYTE * par3, long last);
        BOOL APICALL (*Awebactive)(struct AwebSupportIFace *Self);
        void APICALL (*Freefontalias)(struct AwebSupportIFace *Self, struct Fontalias * last);
        struct Fontalias * APICALL (*Addfontalias)(struct AwebSupportIFace *Self, void * par1, UBYTE * last);
        void APICALL (*Freestemvar)(struct AwebSupportIFace *Self, UBYTE * last);
};

#endif /* AWEBPLUGIN_INTERFACE_DEF_H */
