#ifndef AWEBSUBTASK_INTERFACE_DEF_H
#define AWEBSUBTASK_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 50.13.
** Do not edit
*/

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#include "task.h"

struct AwebSubtaskIFace
{
   struct InterfaceData Data;

   ULONG APICALL (*Obtain)(struct AwebSubtaskIFace *Self);
   ULONG APICALL (*Release)(struct AwebSubtaskIFace *Self);
   void APICALL (*Expunge)(struct AwebSubtaskIFace *Self);
   struct Interface * APICALL (*Clone)(struct AwebSubtaskIFace *Self);
   Subtaskfunction * (*AwebGetTaskFunc)(struct AwebSubtaskIFace *Self, ULONG id) APICALL;
};

#endif /* AWEBSUBTASK_INTERFACE_DEF_H */
