#ifndef AWEBSTARTUP_INTERFACE_DEF_H
#define AWEBSTARTUP_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 50.13.
** Do not edit
*/

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_AWEBSTARTUP_H
#include <libraries/awebstartup.h>
#endif

struct AwebStartupIFace
{
   struct InterfaceData Data;

   ULONG APICALL (*Obtain)(struct AwebStartupIFace *Self);
   ULONG APICALL (*Release)(struct AwebStartupIFace *Self);
   void APICALL (*Expunge)(struct AwebStartupIFace *Self);
   struct Interface * APICALL (*Clone)(struct AwebStartupIFace *Self);
   void APICALL (*AwebStartupOpen)(struct AwebStartupIFace *Self, struct Screen * screen, UBYTE * version, ULONG * imagepalette, UBYTE * imagedata);
   void APICALL (*AwebStartupState)(struct AwebStartupIFace *Self, ULONG state);
   void APICALL (*AwebStartupLevel)(struct AwebStartupIFace *Self, long ready, long total);
   void APICALL (*AwebStartupClose)(struct AwebStartupIFace *Self);
};

#endif /* AWEBSTARTUP_INTERFACE_DEF_H */
