#ifndef PLUGIN_INTERFACE_DEF_H
#define PLUGIN_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 50.13.
** Do not edit
*/

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#define LibraryManagerIFace LibraryManagerInterface

#endif /* PLUGIN_INTERFACE_DEF_H */
